CREATE USER TRUNGTQ IDENTIFIED by 123;

GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO TRUNGTQ;

grant connect,resource to demo_trungtq; 

CREATE TABLE HO_SO(
ID_HS char(10) PRIMARY KEY,
TEN_HS VARCHAR2(50),
MO_TA VARCHAR2(200),
NGUOI_TAO_ID NUMBER(10),
NGAY_TAO DATE,
NGAY_GUI DATE,
TEN_FILE VARCHAR2(50),
DINH_DANG CHAR(10),
DON_VI_ID NUMBER(10),
LOAI_HS_ID NUMBER(10),
NGUOI_KY_ID NUMBER(10),
NGAY_KY DATE
);
CREATE TABLE CAN_BO(
CB_ID NUMBER(10) PRIMARY KEY,
HO_TEN VARCHAR(30),
CHUC_VU_ID NUMBER(10)
);
-----

CREATE TABLE DON_VI(
DV_ID NUMBER(10) PRIMARY KEY,
TEN_DV VARCHAR2(50)
);

-----
CREATE TABLE LOAI_HO_SO(
LOAI_HS_ID NUMBER(10) PRIMARY KEY,
TEN_LOAI_HS VARCHAR2(50)
);
----
CREATE TABLE CHUC_VU(
CHUC_VU_ID NUMBER(10) PRIMARY KEY,
TEN_CHUC_VU VARCHAR2(30)
);
------- 

ALTER TABLE HO_SO
ADD CONSTRAINT FK_LOAI_HS_ID FOREIGN KEY (LOAI_HS_ID) REFERENCES LOAI_HO_SO(LOAI_HS_ID);

ALTER TABLE HO_SO
ADD CONSTRAINT FK_DON_VI_ID FOREIGN KEY (DON_VI_ID) REFERENCES DON_VI(DV_ID);

ALTER TABLE HO_SO
ADD CONSTRAINT FK_NGUOI_TAO_ID FOREIGN KEY (NGUOI_TAO_ID) REFERENCES CAN_BO(CB_ID);

ALTER TABLE HO_SO
ADD CONSTRAINT FK_NGUOI_KY_ID FOREIGN KEY (NGUOI_KY_ID) REFERENCES CAN_BO(CB_ID);

ALTER TAblE CAN_BO
ADD CONSTRAINT FK_CHUC_VU_ID FOREIGN KEY (CHUC_VU_ID) REFERENCES CHUC_VU(CHUC_VU_ID);

ALTER TABLE DON_VI
  ADD ma_cha number(10);

ALTER TABLE DON_VI
ADD CONSTRAINT FK_MA_CHA FOREIGN KEY (MA_CHA) REFERENCES DON_VI(DV_ID);

CREATE SEQUENCE SEQ_ID_HS
MINVALUE 0
MAXVALUE 10000
START WITH 1
INCREMENT by 1
nocycle
nocache;

CREATE SEQUENCE SEQ_ID_DV
MINVALUE 0
MAXVALUE 10000
START WITH 1
INCREMENT by 1
nocycle
nocache;

CREATE SEQUENCE SEQ_ID_CanBo
MINVALUE 0
MAXVALUE 10000
START WITH 1
INCREMENT by 1
nocycle
nocache;
CREATE SEQUENCE SEQ_ID_LoaiHS
MINVALUE 0
MAXVALUE 10000
START WITH 1
INCREMENT by 1
nocycle
nocache;
CREATE SEQUENCE SEQ_ID_ChucVu
MINVALUE 0
MAXVALUE 10000
START WITH 1
INCREMENT by 1
nocycle
nocache;