--TAO TABLESPACE, USER VA CAP QUYEN CHO USE
create tablespace BH_ONLINE 
DATAFILE 'C:\APP\VANHUNG\VIRTUAL\ORADATA\ORCL\BH_ONLINE.DBF' SIZE 100M
REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 2048M;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER BANHANGONLINE IDENTIFIED BY BH123;

GRANT CONNECT, RESOURCE TO BANHANGONLINE; 

--TAO BANG SAN_PHAM
CREATE TABLE SAN_PHAM
(
MA_SP VARCHAR2(10) PRIMARY KEY,
TEN_SP VARCHAR2(100),
MO_TA VARCHAR2(200),
GIA_MUA NUMBER(12,2),
GIA_BAN NUMBER(12,2),
SO_LUONG NUMBER(9),
THONG_TIN_SAN_PHAM VARCHAR2(200),
TINH_TRANG VARCHAR2(20),
NAM_SX DATE,
BAO_HANH VARCHAR2(20),
NGAY_TAO DATE,
NGUOI_TAO VARCHAR2(10),
NGAY_CAP_NHAT DATE,
NGAY_XB DATE,
XUAT_SU VARCHAR2(10)
);

--TAO BANG MAT HANG
CREATE TABLE MAT_HANG
(
MA_MH VARCHAR2(10) PRIMARY KEY ,
TEN_MH VARCHAR2(100),
MO_TA VARCHAR2(150)
);

--TAO BANG HANG SAN XUAT
CREATE TABLE HANG_SX
(
MA_HANG_SX VARCHAR2(10) PRIMARY KEY,
TEN_HANG VARCHAR2(100),
DIA_CHI VARCHAR2(150),
EMAIL VARCHAR2(150),
DIEN_THOAI NUMBER(12)
);

--TAO BANG MAT HANG - HANG SAN XUAT
CREATE TABLE MH_HANGSX
(
MA_MH VARCHAR2(10),
MA_HANG_SX VARCHAR2(10),
CONSTRAINT PK_MH_SX_ID PRIMARY KEY (MA_MH, MA_HANG_SX)
);

--TAO BANG XUAT SU
CREATE TABLE XUAT_SU 
(
MA_XS VARCHAR2(10) PRIMARY KEY,
TEN_XS VARCHAR2(50)
);

--TAO BANG NHAN VIEN
CREATE TABLE NHAN_VIEN
(
MA_NV VARCHAR2(10) PRIMARY KEY,
HO_TEN VARCHAR2(50),
GIOI_TINH CHAR(1),
NGAY_SINH DATE,
EMAIL VARCHAR2(150),
DIA_CHI VARCHAR2(150),
DIEN_THOAI NUMBER(10),
LUONG NUMBER(12,2)
);

--TAO BANG KHACH HANG
CREATE TABLE KHACH_HANG
(
MA_KH VARCHAR2(10) PRIMARY KEY,
HO_TEN VARCHAR2(50),
DIA_CHI VARCHAR2(150),
DIEN_THOAI NUMBER(10),
LOAI_KH VARCHAR2(10)
);

--TAO BANG LOAI KHACH HANG
CREATE TABLE LOAI_KH
(
MA_KH VARCHAR2(10) PRIMARY KEY,
LOAI_KH VARCHAR2(50)
);

--TAO BANG HOA DON BAN
CREATE TABLE HOA_DON_BAN
(
MA_HD VARCHAR2(10) PRIMARY KEY,
TEN_HD VARCHAR2(50),
MA_KH VARCHAR2(10),
MO_TA VARCHAR2(150),
NGAY_BAN DATE
);

--TAO BANG HOA DON BAN CHI TIET
CREATE TABLE HOA_DON_BAN_CT
(
MA_HD VARCHAR2(10),
MA_SP VARCHAR2(10),
SO_LUONG NUMBER(5),
GIA_BAN NUMBER(12,2)
);



--QUAN HE GIUA MAT_HANG VOI MH_HANGSX
ALTER TABLE MH_HANGSX
ADD CONSTRAINT FK_MH_MHHANGSX_ID FOREIGN KEY (MA_MH) REFERENCES MAT_HANG(MA_MH);

--QUANHE GIUA HANG_SX VOI MH_HANGSX
ALTER TABLE MH_HANGSX
ADD CONSTRAINT FK_HANGSX_MHHANGSX_ID FOREIGN KEY (MA_HANG_SX) REFERENCES HANG_SX(MA_HANG_SX);

--QUAN HE GIUA SAN_PHAM VOI NHAN_VIEN
ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_SP_NHANVIEN_ID FOREIGN KEY (NGUOI_TAO) REFERENCES NHAN_VIEN(MA_NV);

--QUAN HE GIUA SAN_PHAM VOI HOA_DON_BAN_CT
ALTER TABLE HOA_DON_BAN_CT
ADD CONSTRAINT FK_SP_HOA_DON_BAN_CT_ID FOREIGN KEY(MA_SP) REFERENCES SAN_PHAM(MA_SP);

--QUAN HE GIUA XUAT_SU VOI SAN_PHAM
ALTER TABLE SAN_PHAM
ADD CONSTRAINT FK_SP_XS_ID FOREIGN KEY (XUAT_SU) REFERENCES XUAT_SU(MA_XS);

--QUAN HE GIUA KHACH_HANG VOI LOAI_KH
ALTER TABLE KHACH_HANG
ADD CONSTRAINT FK_KH_LOAIKH_ID FOREIGN KEY (LOAI_KH) REFERENCES LOAI_KH(MA_KH);

--QUAN HE GIUA KHACH_HANG VOI HOA_DON_BAN
ALTER TABLE HOA_DON_BAN
ADD CONSTRAINT FK_KH_HOA_DON_BAN_ID FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KH);

