--Các tài liệu, hồ sơ bao gồm các thông tin chính: Mã hồ sơ, Tên hồ sơ, Mô tả Người tạo, Ngày tạo, Ngày gửi, Ngày nhận, Tên file, định dạng, Đơn vị, Loại hồ sơ, Người ký, Ngày ký,...
CREATE TABLE HO_SO
(
MA_HO_SO VARCHAR2(10) PRIMARY KEY,
TEN_HO_SO VARCHAR2(150),
MO_TA VARCHAR2(250),
NGUOI_TAO_ID VARCHAR2(10),
NGAY_TAO  DATE,
NGAY_GUI DATE,
NGAY_NHAN DATE,
TEN_FILE VARCHAR2(50),
DINH_DANG VARCHAR2(10),
MA_DON_VI VARCHAR2(10),
LOAI_HO_SO NUMBER(2),
NGUOI_KY VARCHAR2(10),
NGAY_KY DATE
);
-- Loại hồ sơ sử dụng để phân loại tài liệu, hồ sơ được gửi đi hoặc gửi đến công ty
CREATE TABLE LOAI_HO_SO
(
MA_LOAI NUMBER(2) PRIMARY KEY,
TEN_LOAI VARCHAR2(50)
);
-- Đơn vị sử dụng để lưu trữ các thông tin về các đơn vị, tổ chức liên quan trong.
CREATE TABLE DON_VI
(
MA_DON_VI VARCHAR2(10) PRIMARY KEY,
TEN_DON_VI VARCHAR2(50),
MA_CHA VARCHAR2(10)
);
-- Thông tin cán bộ sử dụng để lưu trữ các thông tin về cán bộ trong công ty để xác định các thông tin liên quan trong tài liệu, hồ sơ như người tạo, người ký.
CREATE TABLE CAN_BO
(
MA_CAN_BO VARCHAR2(10) PRIMARY KEY,
HO_TEN VARCHAR2(50),
GIOI_TINH CHAR(1),
NGAY_SINH DATE,
DIEN_THOAI NUMBER(10),
EMAIL VARCHAR2(100),
DIA_CHI VARCHAR2(50),
CHUC_VU_ID VARCHAR2(10),
DON_VI_ID VARCHAR2(10)
);
-- Thông tin về chức vụ để xác định vị trí của người đó trong công ty.
CREATE TABLE CHUC_VU
(
MA_CHUC_VU VARCHAR2(10) PRIMARY KEY,
TEN_CHUC_VU VARCHAR2(50)
);

--THIET LAO QUAN HE 
--THIET LAP QUAN HE GIUA BANG CAN BO VA DON VI
ALTER TABLE CAN_BO
ADD CONSTRAINT FK_DONVI_ID FOREIGN KEY (DON_VI_ID)
REFERENCES DON_VI(MA_DON_VI);

--THIET LAP QUAN HE GIUA BANG CAN BO VA CHUC VU
ALTER TABLE CAN_BO
ADD CONSTRAINT FK_CHUCVU_ID FOREIGN KEY (CHUC_VU_ID)
REFERENCES CHUC_VU(MA_CHUC_VU);

--THIET LAP QUAN HE GIUA BANG HO SO VA LOAI HO SO
ALTER TABLE HO_SO
ADD CONSTRAINT FK_LOAIHOSO_ID FOREIGN KEY (LOAI_HO_SO)
REFERENCES LOAI_HO_SO(MA_LOAI);

--THIET LAP QUAN HE GIUA BANG HO SO VA DON VI
ALTER TABLE HO_SO
ADD CONSTRAINT FK_HOSO_DONVI_ID FOREIGN KEY (MA_DON_VI)
REFERENCES DON_VI(MA_DON_VI);

--THET LALP QUAN HE GIUA BANG HO SO VA CAN BO
ALTER TABLE HO_SO
ADD CONSTRAINT FK_HOSO_NGUOITAO_ID FOREIGN KEY (NGUOI_TAO_ID)
REFERENCES CAN_BO(MA_CAN_BO);

ALTER TABLE HO_SO
ADD CONSTRAINT FK_HOSO_NGUOIKY_ID FOREIGN KEY (NGUOI_KY)
REFERENCES CAN_BO(MA_CAN_BO);


--THIET LAP QUAN HE TRING BANG DON VI
ALTER TABLE DON_VI
ADD CONSTRAINT FK_DONVI_MACA_ID FOREIGN KEY (MA_CHA)
REFERENCES DON_VI (MA_DON_VI);

