--Sách ???c qu?n lý trong th? vi?n ???c phân lo?i theo t?ng ch? ?? nh? Kinh t?, Toán h?c, Tin h?c, Ngo?i ng?,…
CREATE TABLE SACH
(
MA_SACH VARCHAR2(10) PRIMARY KEY,
LOAI_SACH VARCHAR2(50)
);

--Thông tin sách c?n qu?n lý trong h? th?ng bao g?m các thông tin nh? sau: Mã sách, Tên sách,
--Mô t?, Giá mua, S? ??u sách, S? trang , Ngày mua, Ch? ??.
CREATE TABLE TT_SACH
(
MA_SACH VARCHAR2(10) PRIMARY KEY,
TEN_SACH VARCHAR2(50),
MO_TA VARCHAR2(200),
GIA_MUA NUMBER(10,2),
SO_DAU_SACH NUMBER(3),
SO_TRANG NUMBER(5),
NGAY_MUA DATE,
CHU_DE VARCHAR2(10),
MA_LOAI_SACH VARCHAR2(10)
);

--Thông tin sinh viên m??n ???c l?u trong h? th?ng bao g?m các thông tin: Mã SV, H? tên,
--Gi?i tính, Ngày sinh, ?i?n tho?i, Email, ??a ch?.
CREATE TABLE SINH_VIEN
(
MA_SV VARCHAR2(10) PRIMARY KEY,
HO_TEN VARCHAR2(50),
GIOI_TINH VARCHAR2(4),
NGAY_SINH DATE,
DIEN_THOAI NUMBER(10),
EMAIL VARCHAR2(100),
DIA_CHI VARCHAR2(150)
);

--Sinh viên có th? m??n t?i ?a 4 quy?n sách trong m?t ??t và có th? không m??n quy?n nào.
--M?t sách có th? có nhi?u sinh viên m??n n?u còn trong th? vi?n. Khi m??n h? th?ng s? ghi
--ngày m??n.
CREATE TABLE SINHVIEN_MUONSACH
(
MA_SV VARCHAR2(10),
MA_SACH VARCHAR2(10),
SO_LUONG NUMBER(2),
NGAY_MUON DATE,
CONSTRAINT PK_SINHVIEN_SACH PRIMARY KEY (MA_SV, MA_SACH)
);

--Sinh viên ch? ???c phép m??n t?i ?a trong th?i gian là 5 ngày ?? ??m b?o sách có th? cho
--nhi?u sinh viên có th? s? d?ng. Khi tr? sách nhân viên th? vi?n s? ghi thông tin ngày tr?
--sách c?a sinh viên. N?u quá h?n sinh viên ?ó s? b? n?p ph?t v?i m?i ngày quá h?n là 50.000
--??ng.
CREATE TABLE SINHVIEN_TRASACH
(
MA_SV VARCHAR2(10),
MA_SACH VARCHAR2(10),
SOLUONG NUMBER(2),
NGAY_TRA DATE,
CONSTRAINT PK_SINHVIEN_TRASACH PRIMARY KEY(MA_SV, MA_SACH)
);


--QUAN HE GIUA SACH VA TT_SACH
ALTER TABLE TT_SACH
ADD CONSTRAINT FK_TTSACH_SACH_ID FOREIGN KEY (MA_LOAI_SACH) REFERENCES SACH(MA_SACH);


--QUAN HE GIUA SACH VA SINHVIEN_MUONSACH
ALTER TABLE SINHVIEN_MUONSACH
ADD CONSTRAINT FK_SACH_SVMS_ID FOREIGN KEY (MA_SACH) REFERENCES TT_SACH(MA_SACH);

--QUAN HE GIUA SINH_VIEN VA SINHVIEN_MUONSACH
ALTER TABLE SINHVIEN_MUONSACH
ADD CONSTRAINT FK_SINHVIEN_SVMS_ID FOREIGN KEY (MA_SV) REFERENCES SINH_VIEN(MA_SV);

--QUAN HE GIUA SACH VA SINHVIEN_TRASACH
ALTER TABLE SINHVIEN_TRASACH
ADD CONSTRAINT FK_SACH_SVTS_ID FOREIGN KEY (MA_SACH) REFERENCES TT_SACH(MA_SACH);


--QUAN HE GIUA SINH_VIEN VA SINHVIEN_TRASACH
ALTER TABLE SINHVIEN_TRASACH
ADD CONSTRAINT FK_SINHVIEN_SVTS_ID FOREIGN KEY (MA_SV) REFERENCES SINH_VIEN(MA_SV);

ALTER TABLE TT_SACH
MODIFY GIA_MUA NUMBER(7);

--INSERT THONG TIN
--THEM THON GTIN SACCH
INSERT INTO SACH(MA_SACH, LOAI_SACH)
VALUES ('KT', 'KINH TE');
INSERT INTO SACH(MA_SACH, LOAI_SACH)
VALUES ('TOH', 'TOAN HOC');
INSERT INTO SACH(MA_SACH, LOAI_SACH)
VALUES ('TIH', 'TIN HOC');
INSERT INTO SACH(MA_SACH, LOAI_SACH)
VALUES ('NN', 'NGOAI NGU');


--THEM THONG TIN CHO TT_SACH
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('TCC', 'TOAN CAO CAP', 150000, 100, 350, TO_DATE('10-04-2018', 'DD-MM-YYYY'), 'TOAN HOC', 'TOH');
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('TTHCM', 'TU TUONNG HO CHI MINH', 100000, 50, 300, TO_DATE('10/04/2018', 'DD/MM/YYYY'), 'TOAN HOC', 'TOH');
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('KTVM', 'KINH TE VI MO', 120000, 80, 500, TO_DATE('10/04/2018', 'DD/MM/YYYY'), 'KINH TE', 'KT');
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('TA', 'NGU PHAP TIENG ANH CO BAN', 180000, 150, 500, TO_DATE('10/04/2018', 'DD/MM/YYYY'), 'NGOAI NGU', 'NN');
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('CSDL', 'CO SO DU LIEU', 200000, 100, 400, TO_DATE('10/04/2018', 'DD/MM/YYYY'), 'TOAN HOC', 'TOH');
INSERT INTO TT_SACH(MA_SACH, TEN_SACH, GIA_MUA, SO_DAU_SACH, SO_TRANG, NGAY_MUA, CHU_DE, MA_LOAI_SACH)
VALUES ('MMT', 'MANG MAY TINH', 90000, 160, 400, TO_DATE('10/04/2018', 'DD/MM/YYYY'), 'TIN HOC', 'TIH');

--THEM THONG TIN SINH_VIEN
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('001', 'NGUYEN VAN HUNG', 'NAM', TO_DATE('10-02-1997', 'DD-MM-YYYY'), 0123654789, 'HUNG@GMAIL.COM', 'VINH PHUC');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('002', 'NGUYEN QUANG TRUNG', 'NAM', TO_DATE('11-06-1997', 'DD-MM-YYYY'), 0326514789, 'TRUNG@GMAIL.COM', 'VINH PHUC');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('003', 'NGUYEN VAN NAM', 'NAM', TO_DATE('22-08-1996', 'DD-MM-YYYY'), 0987456321, 'NAM@GMAIL.COM', 'HA GIANG');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('004', 'DO VAN NGOC', 'NAM', TO_DATE('11-03-1997', 'DD-MM-YYYY'), 0965874123, 'NGOC@GMAIL.COM', 'PHU THO');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('005', 'NGUYEN HUY TUAN', 'NAM', TO_DATE('10-11-1995', 'DD-MM-YYYY'), 0123659874, 'TUAN@GMAIL.COM', 'HUNG YEN');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('006', 'VU THI MO', 'NU', TO_DATE('10-04-1999', 'DD-MM-YYYY'), 0123695847, 'MO@GMAIL.COM', 'CAO BANG');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('007', 'TRUONG THI NHUNG', 'NU', TO_DATE('21-05-1998', 'DD-MM-YYYY'), 0965321478, 'NHUNG@GMAIL.COM', 'BAC NINH');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('008', 'LE TIEN NAM', 'NAM', TO_DATE('16-12-1997', 'DD-MM-YYYY'), 0136524789, 'NAM@GMAIL.COM', 'HAI DUONG');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('009', 'NGUYEN THI TAM', 'NU', TO_DATE('23-08-1997', 'DD-MM-YYYY'), 0986532147, 'TAM@GMAIL.COM', 'HA NAM');
INSERT INTO SINH_VIEN(MA_SV, HO_TEN, GIOI_TINH, NGAY_SINH, DIEN_THOAI, EMAIL, DIA_CHI)
VALUES ('010', 'NGUYEN VAN KY', 'NAM', TO_DATE('10-12-1997', 'DD-MM-YYYY'), 0123659874, 'KY@GMAIL.COM', 'THANH HOA');


--THEM THONG TIN SINHVIEN_-MUONSACH
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('001', 'TCC', 1, TO_DATE('15-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('003', 'TTHCM', 1, TO_DATE('17-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('005', 'KTVM', 1, TO_DATE('16-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('001', 'KTVM', 1, TO_DATE('15-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('003', 'TA', 1, TO_DATE('17-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('001', 'TTHCM', 1, TO_DATE('05-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('002', 'TCC', 1, TO_DATE('11-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('006', 'CSDL', 1, TO_DATE('20-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('007', 'CSDL', 1, TO_DATE('25-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_MUONSACH(MA_SV, MA_SACH, SO_LUONG, NGAY_MUON)
VALUES('002', 'CSDL', 1, TO_DATE('03-10-2019', 'DD-MM-YYYY'));

--THEM THONG TIN SINHVIEN_TRASACH
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES ('001', 'TCC', 1, TO_DATE('20-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('003', 'TTHCM', 1, TO_DATE('20-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('005', 'KTVM', 1, TO_DATE('28-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('001', 'KTVM', 1, TO_DATE('25-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('003', 'TA', 1, TO_DATE('22-08-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('001', 'TTHCM', 1, TO_DATE('10-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('002', 'TCC', 1, TO_DATE('16-09-2019', 'DD-MM-YYYY'));
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('006', 'CSDL', 1, NULL);
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('007', 'CSDL', 1, NULL);
INSERT INTO SINHVIEN_TRASACH(MA_SV, MA_SACH, SOLUONG, NGAY_TRA)
VALUES('002', 'CSDL', 1, NULL);

--Th?c hi?n l?y thông tin b?ng d? li?u bao g?m các thông tin sau: Mã sách, Tên sách,
--S? trang, s? ??u sách, Giá tr? sách, Tên ch? ??.
SELECT MA_SACH, TEN_SACH, SO_TRANG, SO_DAU_SACH, GIA_MUA, CHU_DE FROM TT_SACH;

--Th?c hi?n th?ng kê top 3 sách có giá tr? cao nh?t trong th? vi?n c?a tr??ng ?ó tính
--trên t?ng ??u sách
SELECT MA_SACH, TEN_SACH, GIA_MUA FROM TT_SACH
WHERE ROWNUM <= 3
ORDER BY GIA_MUA DESC;


--Hi?n th? danh sách l?ch s? m??n sách c?a sinh viên bao g?m các thông tin sau: 
--Mã SV, H? tên, ?i?n tho?i, Email, Mã sách, Tên sách, S? ngày m??n.
SELECT TO_DATE('20-08-2019' , 'DD-MM-YYYY') - TO_DATE('15-08-2019', 'DD-MM-YYYY') AS SONGAYMUON FROM DUAL;
SELECT MA_SV, MA_SACH, NGAY_MUON, NGAY_TRA FROM SINHVIEN_MUONSACH, SINHVIEN_TRASACH TK;

--Th?ng kê các ??u sách ?ã có sinh viên m??n trong h? th?ng
SELECT DISTINCT MA_SACH, TEN_SACH FROM TT_SACH
JOIN SINHVIEN_MUONSACH USING (MA_SACH);


--Th?ng kê danh sách các sinh viên ch?a tr? sách ??n ngày 01/10/2019 trong h? th?ng.
SELECT * FROM SINH_VIEN 
JOIN SINHVIEN_TRASACH USING(MA_SV)
WHERE NGAY_TRA = '01-10-2019';


--Th?ng kê danh sách các sinh viên và các ??u sách ??n h?n tr? th? vi?n.
SELECT * FROM SINH_VIEN
JOIN SINHVIEN_TRASACH USING(MA_SV)
WHERE NGAY_TRA IS NULL;


--Th?ng kê các sinh viên ?ã tr? sách nh?ng b? quá th?i gian và s? ti?n ph?t c?a t?ng
--sinh viên ?ó bao g?m các thông tin sau: Mã SV, H? tên, ?i?n tho?i, Email, Mã sách,
--Tên sách, S? ngày m??n, Ti?n ph?t.
SELECT * FROM SINH_VIEN 